/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./src/components/ui/accordion/AccordionContent.vue')['default']
    AccordionHeader: typeof import('radix-vue')['AccordionHeader']
    AccordionItem: typeof import('./src/components/ui/accordion/AccordionItem.vue')['default']
    AccordionRoot: typeof import('radix-vue')['AccordionRoot']
    AccordionTrigger: typeof import('./src/components/ui/accordion/AccordionTrigger.vue')['default']
    AimBotComponent: typeof import('./src/components/AimBotComponent.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/checkbox/Checkbox.vue')['default']
    DebugComponent: typeof import('./src/components/DebugComponent.vue')['default']
    DebugComponet: typeof import('./src/components/DebugComponet.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    MenuComponet: typeof import('./src/components/MenuComponet.vue')['default']
    MiscComponent: typeof import('./src/components/MiscComponent.vue')['default']
    Slider: typeof import('./src/components/ui/slider/Slider.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs/TabsTrigger.vue')['default']
    VisualComponent: typeof import('./src/components/VisualComponent.vue')['default']
  }
}
