/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccordionContent: typeof import('radix-vue')['AccordionContent']
    AccordionHeader: typeof import('radix-vue')['AccordionHeader']
    AccordionItem: typeof import('radix-vue')['AccordionItem']
    AccordionRoot: typeof import('radix-vue')['AccordionRoot']
    AccordionTrigger: typeof import('radix-vue')['AccordionTrigger']
    DebugComponent: typeof import('./src/components/DebugComponent.vue')['default']
    DebugComponet: typeof import('./src/components/DebugComponet.vue')['default']
    MenuComponet: typeof import('./src/components/MenuComponet.vue')['default']
  }
}
